name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-setuptools python3-pip python3-dev build-essential \
                            libssl-dev libffi-dev libsqlite3-dev libgstreamer1.0-dev \
                            gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
                            gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
                            gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools \
                            gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-pulseaudio \
                            gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 \
                            gstreamer1.0-pipewire
        pip install --upgrade pip
        pip install buildozer cython

    - name: Install Android SDK
      run: |
        sudo apt-get install -y wget unzip openjdk-8-jdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
        unzip commandlinetools-linux-6858069_latest.zip -d android-sdk
        yes | android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=android-sdk "platform-tools" "platforms;android-29" "build-tools;29.0.3"

    - name: Create buildozer.spec
      run: |
        echo "[app]" > buildozer.spec
        echo "title = BleApp" >> buildozer.spec
        echo "package.name = bleapp" >> buildozer.spec
        echo "package.domain = org.example" >> buildozer.spec
        echo "source.include_exts = py,png,jpg,kv,atlas" >> buildozer.spec
        echo "version = 0.1" >> buildozer.spec
        echo "requirements = python3,kivy,bleak" >> buildozer.spec
        echo "orientation = all" >> buildozer.spec
        echo "fullscreen = 1" >> buildozer.spec
        echo "android.arch = arm64-v8a, armeabi-v7a, x86_64" >> buildozer.spec
        echo "android.permissions = INTERNET, ACCESS_NETWORK_STATE, ACCESS_WIFI_STATE, BLUETOOTH, BLUETOOTH_ADMIN" >> buildozer.spec
        echo "android.minapi = 21" >> buildozer.spec
        echo "android.sdk = 30" >> buildozer.spec
        echo "android.ndk = 21b" >> buildozer.spec

    - name: Build APK
      run: |
        buildozer android debug
        ls -la

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: BleApp-release.apk
        path: bin/*.apk
