name: 'Kivy App to APK'

on:
  push:
    branches:
      - main  # or your default branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        architecture: x64
        python-version: '3.8'

    - name: Setup Java 17 required by Gradle
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set JAVA_HOME
      run: echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
      shell: bash

    - name: Prepare virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        echo "Using Python==$(python --version)"
      shell: bash

    - name: Install and upgrade dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        export PATH=$PATH:~/.local/bin/
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install --upgrade Cython==0.29.33 buildozer
      shell: bash

    - name: Install Bleak and other Python requirements
      run: |
        python3 -m pip install bleak
        if [ -f requirements.txt ]; then
          python3 -m pip install -r requirements.txt
        fi
      shell: bash

    - name: Install Android SDK
      run: |
        wget -q "https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip" -O commandlinetools.zip
        unzip -q commandlinetools.zip -d android-sdk
        echo "ANDROID_SDK_ROOT=$PWD/android-sdk" >> $GITHUB_ENV
        export PATH=$PATH:$PWD/android-sdk/cmdline-tools/bin
        yes | sdkmanager --licenses
        sdkmanager "platforms;android-30" "build-tools;35.0.0"
      shell: bash

    - name: Build with Buildozer
      run: buildozer -v android debug
      shell: bash
